# Generated by Django 4.2.7 on 2024-03-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='code',
        ),
    ]
