# Generated by Django 4.2.7 on 2024-03-11 15:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_forum', '0002_rename_user_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(default='Текст объявления'),
        ),
    ]
