# Generated by Django 4.2.7 on 2024-03-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan_forum', '0004_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='Текст объявления'),
        ),
    ]
